import React, {useEffect, useState } from "react";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as Tone from "tone";
import Script from 'next/script'

//import {View} from "react-native"

import Component1 from '../comps/Component1'

export default function Home() {
  const [count, setCount] = useState(0)
  const handleAdd = () =>
  {
    //this.callmemaybe()
    console.log("FUNCTION CALLED")
    //setCount(count+1)
  }
function callmemaybe()
{
  console.log("CALL ME CALLED")
}
  //useEffect filter to get audio to playing otherwise AudioBuffer error will occur
  const [noise, setNoise] = useState(null);
    const [playing, setPlaying] = useState(false);
    const [autoFilter, setAutoFilter] = useState(null);
      const [note, setNote] = useState(false)


    useEffect(() => {
      const synth = new Tone.Synth().toDestination();
      synth.triggerAttackRelease(`${"C"}4`, "8n");
      console.log("played")

    }, [playing,note]);

function notez(key)
{
  //key=key+1
  //setNote(key)
  //console.log(note)
  const synth = new Tone.Synth().toDestination();
  synth.triggerAttackRelease(key, "8n");
  //console.log(key)
  //setPlaying(!playing)
}


    //const synth = new Tone.Synth().toDestination();


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <script
  src="/play_audio.js"
  strategy="beforeInteractive"
/>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

<Component1 handleAdd={handleAdd} />
{count}

  <button className="note" onClick={() => notez("C4")}>
  {"C4"}
  </button>
  <button className="note" onClick={() => notez("C3")}>
  {"C3"}
  </button>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
